### PR TITLE
Feat/create venue model

### PR DESCRIPTION
**Pull request by darchard1984**
What change does this PR introduce?

- Cafe Model created called Venue. Created in Core App.
- init.py re-introduced to core
- migrations created in core
- models.py created in core
- admin.py created in core and Venue model registered
- test_models.py added to tests app
- init.py added to tests app in order to run TestCases

Notes

- Removed apps.py from core, not needed at this stage but may be needed at a later date for app specific configs.

- Ignore the Previous PR of this feature to Develop Branch.

Ticket

    https://trello.com/c/i2vEsK2O/44-create-the-initial-cafe-model

### CODE REVIEW

**Comment by darchard1984** [comment]
Hi guys,

I closed the previous PR and created this one after making a few changes. I realise there was no need to do that and I can just keep pushing commits to this branch until the CI's pass. 

That said, it's still failing, this is the Travis ouput. 

screen shot 2018-10-21 at 14 51 49

It seems to be related to my tests module. However, locally all tests are passing,
screen shot 2018-10-21 at 15 33 38

And the server runs fine...

screen shot 2018-10-21 at 15 35 02

Bit stumped. Any ideas ?

**Comment by CianciuStyles** [comment]
Hello Dafydd,

the reason why on your local machine tests are passing fine while on Travis CI they are not is because you're actually launching tests in two differents ways:

- on your local machine, you're invoking `python3 manage.py test`
- on Travis CI, the test are invoked with `pytest`

If you tried running `pytest` on your local machine, they should be failing as well (they are on my local machine). The error message you're getting from Pytest (`Apps aren't loaded yet.`) is happening because Pytest is not aware that Django is involved, as Django has some setup to do before being able to run its code. To solve this problem:

- you should install `pytest-django` (docs are [here](https://pytest-django.readthedocs.io/en/latest/index.html)), and possibly add this dependency to the `requirements.txt` file;
- you should try running on your local machine `pytest --ds=sharespots.settings` (the `--ds` option is added by `pytest-django` and allows Pytest to make Django do its setup based on the settings file you provide there);
- once you have verified that this new command runs the tests fine, change the `script` section in the `.travis.yml` file to be `pytest --ds=sharespots.settings`.

Let me know if you need further help!

Stefano

**Comment by darchard1984** [comment]
Hi Stefano,

Thanks for this. 

I'll have a look at this tomorrow and see how I get on.

Appreciate it!

D

**Comment by darchard1984** [comment]
Hey Stefano,

I've made the changes you suggested and all pytests pass locally.

I've pushed my commits to the branch.  If you navigate to the branch my commits are there but for some reason they're not showing up in this PR. 

Bit weird. Any ideas ?

Should I just open a new PR ?

D

**Comment by darchard1984** [comment]
Ignore that...

Once I submitted the message it kicked something into gear.

**Comment by CianciuStyles** [comment]
Hello Dafydd,

I think nothing is running at the moment because of some problems with Travis CI itself (at this [page](https://www.traviscistatus.com/), under _Third Party Services_, GitHub is marked as Major Outage). Let's wait for this problem to be resolved, and it everything is still frozen then we can come back and try again.

**Comment by darchard1984** [comment]
Ok cool. No problem

**Pull request merged**
