### PR TITLE
Feat/create venue model

### PR DESCRIPTION
**Pull request by darchard1984**
### What change does this PR introduce?

- Cafe Model created called Venue. Created in Core App.
- __init__.py re-introduced to core
- migrations created in core
- models.py created in core 
- admin.py created in core and Venue model registered
- test_models.py added to tests app
- __init__.py added to tests app in order to run TestCases

### Notes

 - Wasn't sure if you guys wanted a new Venues App creating to house the model, for now it's part of the core App.

### Ticket

- [https://trello.com/c/i2vEsK2O/44-create-the-initial-cafe-model]()

### Screenshots

_Visuals that may help the reviewer_

### CODE REVIEW

**Comment by CianciuStyles** [comment]
For some reason it looks like you have replayed all the commits so far in your branch... How did you create it?

**Comment by darchard1984** [comment]
Hey

Ah... apologies this is the first time I've contributed to a team project. 

- So I git cloned the repo
- did a git branch <branch-name>
- made my changes
- did a couple of commits and then a git push origin <branch-name>
- Created my pull request with deveop as base and my branch as head.

Have I missed something ?

D

**Comment by CianciuStyles** [comment]
I've just had a quick look at the develop branch, and it seems to be one of the oldest ones around, which might explain why your PR is replaying a lot of commits already in master... Any specific reasons why you chose develop as base instead of master?

**Comment by darchard1984** [comment]
Hey 

Yeh I chose the "develop" branch because I was following the Contributing Guidelines in the Repo? 

See the link, Point 3.

https://github.com/PolyglotDevsLondon/sharespots/blob/master/CONTRIBUTING.md

Want me to raise a new pull request to master ?

Best

D

**Comment by CianciuStyles** [comment]
You make an excellent point: technically you did the right thing by opening the PR against develop if the Contributing Guidelines say so. At the same time, all the other PR that have been merged so far are against master, so maybe it would be better _for this time_ to open a new one directly against master, and possibly open a new ticket to move the develop branch to more recent commits (@lili2311 what do you think about this?)

**Comment by darchard1984** [comment]
Sure thing..

I'll wait for @lili2311 to confirm what she'd like me to do. 

D

**Comment by lili2311** [comment]
👋 So this is something that has not been clarified. So ideally yes we should open a PR to develop then to master only merge develop.

Sorry for not clarifying, I reviwed the other PR as I did not see this one. Let's keep the one to master and I will fix develop to catch up with master then announce this properly so there is no confusion and we can follow the standard from then on.

**Comment by lili2311** [comment]
I will close this one as it is replaying all the commits missing in develop since we neglected develop so far.

**Pull request closed without merging**
